[files]
extend-exclude = [
    ".git/",
    ".github/workflows/typo_config.toml",
    "assets/js/*.min.*",
]
ignore-hidden = false
[default]
extend-ignore-re = [
    "Brain tailoRed stImulation protocoL",
    "Vas Vasiliadis",
]
[default.extend-words]
Vas = "Vas"
protoco = "protoco"
